import './globals.css'
import type { Metadata } from 'next'

import { Montserrat_Alternates } from 'next/font/google'

import { ApolloWrapper } from "@/lib/client";
import { AppStateProvider } from "@/store";


import ReduxProvider from "../storiesRedux/storeProvider"

const inter = Montserrat_Alternates({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <AppStateProvider>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </AppStateProvider>
        </ApolloWrapper>
      </body>
    </html >
  )
}
